pipeline:
  test_smoke:
    image: python:3-slim
    secrets:
      - vscale_api_token
    commands:
      - pip3 install -r requirements.txt
      - ./vscalectl.py --help
      - python3 tests_vscalectl.py
    when:
      branch:
        exclude:
          - dev

  build:
    image: python:3-slim
    commands:
      - apt-get update -qq
      - apt-get install binutils jq curl tree -qqy
      - pip3 install -r requirements.txt
      - pip3 install pyinstaller
      - pyinstaller -n $(bash util/build_name_generate.sh) --onefile vscalectl.py
      - tree
    when:
      branch:
        - master
        - int

  s3:
    image: plugins/s3
    bucket: vscalectl-public
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: dist/*
    target: /
    strip_prefix: dist/
    path_style: true
    endpoint: http://minio.agrrh.com:9000
    when:
      branch:
        - master
        - int

  telegram:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    message: |
      build #{{build.number}} failed!
      link: {{build.link}}
    when:
      status: failure
