pipeline:
  test_smoke:
    image: python:3-slim
    secrets:
      - vscale_api_token
    commands:
      - pip3 install -r requirements.txt
      - ./vscalectl.py --help
      - python3 tests_vscalectl.py

  build:
    image: python:3-slim
    commands:
      - apt-get update -qq
      - apt-get install binutils jq curl -qqy
      - pip3 install -r requirements.txt
      - pip3 install pyinstaller
      - bash util/build_name_generate.sh
      - pyinstaller -n vscalectl-$${VSCALECTL_VERSION} --onefile vscalectl.py
    when:
      branch:
        - master
        - int

  telegram:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    message: |
      build #{{build.number}}
      link: {{build.link}}
    when:
      status: failure

  s3:
    image: plugins/s3
    secrets:
      - minio_access_key
      - minio_secret_key
    bucket: vscalectl-public
    access_key: $${MINIO_ACCESS_KEY}
    secret_key: $${MINIO_SECRET_KEY}
    source: .
    target: /
    path_style: true
    endpoint: http://minio.agrrh.com:9000/
    when:
      branch:
        - master
        - int
