pipeline:
  test_smoke:
    image: python:3-slim
    environment:
      - VSCALE_API_TOKEN=invalid-but-its-okay
    commands:
      - pip3 install -r requirements.txt
      - ./vscalectl.py --help

  test_functional:
    image: python:3-slim
    commands:
      - export VSCALE_API_TOKEN=$${VSCALE_API_TOKEN}
      - echo ${VSCALE_API_TOKEN}
      - export VSCALE_API_TOKEN=${vscale_api_token}
      - echo ${VSCALE_API_TOKEN}
      - pip3 install -r requirements.txt
      - python3 tests_vscalectl.py

  build:
    image: python:3-slim
    commands:
      - apt-cache update -qq
      - apt-get install binutils -qqy
      - pip3 install -r requirements.txt
      - pip3 install pyinstaller
      - pyinstaller --onefile vscalectl.py
    when:
      branch: master

  telegram:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    message: >
      build #{{build.number}}
      link: {{build.link}}
    when:
      status: changed

  telegram_distribute:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    document: dist/vscalectl
    when:
      branch: master
