pipeline:
  test_smoke:
    image: python:3-slim
    environment:
      - VSCALE_API_TOKEN=invalid-but-its-okay
    commands:
      - pip3 install -r requirements.txt
      - ./vscalectl.py --help

  build:
    image: python:3-slim
    commands:
      - apt-cache update -qq
      - apt-get install binutils -qqy
      - pip3 install -r requirements.txt
      - pip3 install pyinstaller
      - pyinstaller --onefile vscalectl.py
    when:
      branch: master

  telegram_master:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    document: dist/vscalectl
    when:
      branch: master

  telegram_dev:
    image: appleboy/drone-telegram
    secrets:
      - telegram_token
      - telegram_to
    when:
      branch:
        exclude: master
